name: Sirvia-official-website

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download code
      uses: actions/checkout@v1
    - name: Build and Deploy
      uses: actions/setup-node@v1
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master
        FOLDER: dist/index.html
        BUILD_SCRIPT: npm install && npm run build
