name: Sirvia-official-website

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download code
      uses: actions/checkout@v1
    - name: Node deploy
      uses: actions/setup-node@v1
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER:
        BUILD_SCRIPT: npm install && npm run build
